# Generated by Django 4.2.20 on 2025-03-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_groupconversation_groupmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='GroupConversation',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
